-- DuckDB source tables. Run with 02-04 in the runner's transaction.
-- CREATE OR REPLACE refreshes source tables; the runner backs up an existing database first.
-- Quarter/month keys stay text to preserve the existing dashboard contract.

CREATE OR REPLACE TABLE macro_regime_signals (
    "quarter" VARCHAR PRIMARY KEY,
    "us_regime" VARCHAR NOT NULL,
    "eurozone_regime" VARCHAR NOT NULL,
    "regime_divergence" BOOLEAN NOT NULL,
    CHECK (regexp_full_match("quarter", '[0-9]{4}Q[1-4]')),
    CHECK (us_regime IN ('Goldilocks', 'Overheating', 'Stagflation', 'Deflationary Slowdown')),
    CHECK (eurozone_regime IN ('Goldilocks', 'Overheating', 'Stagflation', 'Deflationary Slowdown')),
    CHECK (regime_divergence = (us_regime <> eurozone_regime))
);

CREATE OR REPLACE TABLE monthly_market_signals (
    "month" VARCHAR PRIMARY KEY,
    "us_policy_rate" DOUBLE NOT NULL,
    "us_cpi_yoy" DOUBLE,
    "us_real_policy_rate" DOUBLE,
    "us_2y_yield" DOUBLE NOT NULL,
    "us_real_2y_rate" DOUBLE,
    "us_2y_policy_gap" DOUBLE NOT NULL,
    "eurozone_policy_rate" DOUBLE NOT NULL,
    "hicp_yoy" DOUBLE NOT NULL,
    "eurozone_real_policy_rate" DOUBLE NOT NULL,
    "eurozone_2y_yield" DOUBLE NOT NULL,
    "eurozone_real_2y_rate" DOUBLE NOT NULL,
    "eurozone_2y_policy_gap" DOUBLE NOT NULL,
    "us_10y_yield" DOUBLE NOT NULL,
    "us_10y_2y_spread" DOUBLE NOT NULL,
    "us_curve_regime" VARCHAR NOT NULL,
    "eurozone_10y_yield" DOUBLE NOT NULL,
    "eurozone_10y_2y_spread" DOUBLE NOT NULL,
    "eurozone_curve_regime" VARCHAR NOT NULL,
    "germany_10y_yield" DOUBLE NOT NULL,
    "italy_10y_yield" DOUBLE NOT NULL,
    "italy_germany_10y_spread" DOUBLE NOT NULL,
    "spread_change" DOUBLE NOT NULL,
    CHECK (regexp_full_match("month", '[0-9]{4}-(0[1-9]|1[0-2])')),
    CHECK ("us_policy_rate" IS NULL OR isfinite("us_policy_rate")),
    CHECK ("us_cpi_yoy" IS NULL OR isfinite("us_cpi_yoy")),
    CHECK ("us_real_policy_rate" IS NULL OR isfinite("us_real_policy_rate")),
    CHECK ("us_2y_yield" IS NULL OR isfinite("us_2y_yield")),
    CHECK ("us_real_2y_rate" IS NULL OR isfinite("us_real_2y_rate")),
    CHECK ("us_2y_policy_gap" IS NULL OR isfinite("us_2y_policy_gap")),
    CHECK ("eurozone_policy_rate" IS NULL OR isfinite("eurozone_policy_rate")),
    CHECK ("hicp_yoy" IS NULL OR isfinite("hicp_yoy")),
    CHECK ("eurozone_real_policy_rate" IS NULL OR isfinite("eurozone_real_policy_rate")),
    CHECK ("eurozone_2y_yield" IS NULL OR isfinite("eurozone_2y_yield")),
    CHECK ("eurozone_real_2y_rate" IS NULL OR isfinite("eurozone_real_2y_rate")),
    CHECK ("eurozone_2y_policy_gap" IS NULL OR isfinite("eurozone_2y_policy_gap")),
    CHECK ("us_10y_yield" IS NULL OR isfinite("us_10y_yield")),
    CHECK ("us_10y_2y_spread" IS NULL OR isfinite("us_10y_2y_spread")),
    CHECK ("eurozone_10y_yield" IS NULL OR isfinite("eurozone_10y_yield")),
    CHECK ("eurozone_10y_2y_spread" IS NULL OR isfinite("eurozone_10y_2y_spread")),
    CHECK ("germany_10y_yield" IS NULL OR isfinite("germany_10y_yield")),
    CHECK ("italy_10y_yield" IS NULL OR isfinite("italy_10y_yield")),
    CHECK ("italy_germany_10y_spread" IS NULL OR isfinite("italy_germany_10y_spread")),
    CHECK ("spread_change" IS NULL OR isfinite("spread_change"))
);

CREATE OR REPLACE TABLE cross_asset_quarterly (
    "quarter" VARCHAR PRIMARY KEY,
    "us_regime" VARCHAR NOT NULL,
    "eurozone_regime" VARCHAR NOT NULL,
    "regime_divergence" BOOLEAN NOT NULL,
    "sp500_return" DOUBLE NOT NULL,
    "eurostoxx50_return" DOUBLE NOT NULL,
    "eurusd_return" DOUBLE NOT NULL,
    "us_baa_10y_spread" DOUBLE NOT NULL,
    "baa_spread_qoq_change" DOUBLE NOT NULL,
    "us_10y_2y_spread" DOUBLE NOT NULL,
    "eurozone_10y_2y_spread" DOUBLE NOT NULL,
    "italy_germany_10y_spread" DOUBLE NOT NULL,
    "us_expected_real_2y_rate" DOUBLE NOT NULL,
    "eurozone_expected_real_2y_rate" DOUBLE NOT NULL,
    "us_10y_yield" DOUBLE NOT NULL,
    "eurozone_10y_yield" DOUBLE NOT NULL,
    "us_10y_qoq_change" DOUBLE,
    "eurozone_10y_qoq_change" DOUBLE,
    "us_10y_direction" VARCHAR NOT NULL,
    "eurozone_10y_direction" VARCHAR NOT NULL,
    "fragmentation_signal" VARCHAR NOT NULL,
    "equity_signal" VARCHAR NOT NULL,
    "credit_signal" VARCHAR NOT NULL,
    "curve_signal" VARCHAR NOT NULL,
    "forward_real_rate_signal" VARCHAR NOT NULL,
    "us_equity_signal" VARCHAR NOT NULL,
    "us_credit_signal" VARCHAR NOT NULL,
    "us_curve_signal" VARCHAR NOT NULL,
    "us_real_rate_signal" VARCHAR NOT NULL,
    "eurozone_equity_signal" VARCHAR NOT NULL,
    "eurozone_curve_signal" VARCHAR NOT NULL,
    "eurozone_real_rate_signal" VARCHAR NOT NULL,
    "eurozone_fragmentation_signal" VARCHAR NOT NULL,
    "us_market_stress_count" BIGINT NOT NULL,
    "eurozone_market_stress_count" BIGINT NOT NULL,
    "macro_market_configuration" VARCHAR NOT NULL,
    CHECK (regexp_full_match("quarter", '[0-9]{4}Q[1-4]')),
    CHECK (us_regime IN ('Goldilocks', 'Overheating', 'Stagflation', 'Deflationary Slowdown')),
    CHECK (eurozone_regime IN ('Goldilocks', 'Overheating', 'Stagflation', 'Deflationary Slowdown')),
    CHECK (regime_divergence = (us_regime <> eurozone_regime)),
    CHECK (us_market_stress_count BETWEEN 0 AND 3),
    CHECK (eurozone_market_stress_count BETWEEN 0 AND 3),
    CHECK (macro_market_configuration IN ('Multi-Channel Stress', 'No Multi-Channel Stress')),
    CHECK ("sp500_return" IS NULL OR isfinite("sp500_return")),
    CHECK ("eurostoxx50_return" IS NULL OR isfinite("eurostoxx50_return")),
    CHECK ("eurusd_return" IS NULL OR isfinite("eurusd_return")),
    CHECK ("us_baa_10y_spread" IS NULL OR isfinite("us_baa_10y_spread")),
    CHECK ("baa_spread_qoq_change" IS NULL OR isfinite("baa_spread_qoq_change")),
    CHECK ("us_10y_2y_spread" IS NULL OR isfinite("us_10y_2y_spread")),
    CHECK ("eurozone_10y_2y_spread" IS NULL OR isfinite("eurozone_10y_2y_spread")),
    CHECK ("italy_germany_10y_spread" IS NULL OR isfinite("italy_germany_10y_spread")),
    CHECK ("us_expected_real_2y_rate" IS NULL OR isfinite("us_expected_real_2y_rate")),
    CHECK ("eurozone_expected_real_2y_rate" IS NULL OR isfinite("eurozone_expected_real_2y_rate")),
    CHECK ("us_10y_yield" IS NULL OR isfinite("us_10y_yield")),
    CHECK ("eurozone_10y_yield" IS NULL OR isfinite("eurozone_10y_yield")),
    CHECK ("us_10y_qoq_change" IS NULL OR isfinite("us_10y_qoq_change")),
    CHECK ("eurozone_10y_qoq_change" IS NULL OR isfinite("eurozone_10y_qoq_change"))
);
